name: CI
# on: [push, pull_request]
on:
  schedule:
    # run every 5 min, for testing
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn
      - name: Default test
        uses: ./
        with:
          command: "node ./tests/script.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
